[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# Test configuration
test = "test"
cache_path = "cache_forge"
force = false
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = true

# Gas configuration
gas_limit = 9223372036854775807
gas_price = 20000000000